apiVersion: delivery.ocm.software/v1alpha1
kind: Localization
metadata:
  name: podinfo-deployment
  namespace: ocm-system
spec:
  interval: 5m
  sourceRef:
    kind: Resource
    name: podinfo-deployment
  configRef:
    kind: ComponentVersion
    name: podinfo
    resourceRef:
      name: config
